export const filters = {
  monster: "monster",
  melee: "melee",
  human: "human",
  agile: "agile",
  god: "god",
  aerial: "aerial",
  strong: "strong",
  grappling: "grappling",
  defend: "defend",
  attack: "attack",
  block: "block",
  mercenary: "mercenary",
  demon: "demon",
  robot: "robot",
  magic: "magic",
  ranged: "ranged",
  alien: "alien",
  ghost: "ghost",
  grapple: "grapple",
  animal: "animal",
  my_team: "my team",
};
